# Numpy Library Primer

Numpy ist ein leistungsfähige Bibliothek in Python für mathematische Operation. Die Bibliothek ist bedeutend schneller als eine Umsetzung in reinem Python Code da sie intern auf C aufsetzt und Berechnungen systemnahe durchführt.

In [1]:
# zuerst muss numpy importiert werden. Das Kürzel np hat sich dafür durchgesetzt
import numpy as np

In [6]:
a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3], # a matrix
             [4,5,6,7]])
d = np.zeros((2,4))#(2x4 matrix of zeros)
e = np.random.rand(2,5) # random 2x5 --> 2 und 5 sind die Dimensionen der Matrix (Zeilen, Spalten)
# matrix with all numbers between 0 and 1
print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.67448783  0.39026618  0.05808151  0.21443228  0.85040931]
 [ 0.53050004  0.01724018  0.06594078  0.61996109  0.90310194]]


Numpy ermöglicht das einfache Erstellen von Vektoren und Matrizen. Die gebräuchlichsten sind in obiger Zelle dargestellt. Numpy unterscheidet dabei nicht explizit zwischen Vektoren und Matrizen. Vektoren sind einfach Matrizen mit nur einer Dimension. Wie in der Mathematik behandelt auch numpy Matrizendimensionen in der Form: (rows, columns)

In [8]:
print( a * 0.1 )# multiplies every number in vector "a" by 0.1
print( c * 0.2 )# multiplies every number in matrix "c" by 0.2
print( a * b )# multiplies elementwise between a and b (columns paired up)
print( a * b * 0.2 )# elementwise multiplication then multiplied by 0.2
print( a * c )# since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"

print( a * e )# since a and e don't have the same number of columns, this
# throws a "Value Error: operands could not be broadcast together with.."

[ 0.   0.1  0.2  0.3]
[[ 0.   0.2  0.4  0.6]
 [ 0.8  1.   1.2  1.4]]
[ 0  5 12 21]
[ 0.   1.   2.4  4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

Numpy führt bei Matrix/Vektor Operationen immer jene Variante aus, die am besten geeignet erscheint.

Beispiel: a ist ein Vektor, daher führt numpy eine Multiplikation Vektor x Skalar durch

Dies kann jedoch auch häufig zu Missverständnissen führen und manche Fehlermeldungen erscheinen auf den ersten Blick nicht schlüssig. Meist hilft es in diesen Fällen, die Dimensionen der np.arrays zu betrachten

In [10]:
a = np.zeros((1,4)) # vector of length 4
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns
c = a.dot(b)
print( c.shape )

(1, 3)


.T = transpose "transponiert" die Matrix, dreht also die Dimensionen um

In [11]:
b = np.zeros((4,3))
print( "c.shape: ", c.shape)
print( "c.T.shape: ", c.T.shape)

c.shape:  (1, 3)
c.T.shape:  (3, 1)
