# Gradient Descent Algorithmus

In [2]:
weight, goal_pred, input = (0.0, 0.8, 0.5)

for iteration in range(4):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.6400000000000001 Prediction:0.0
Error:0.3600000000000001 Prediction:0.2
Error:0.2025 Prediction:0.35000000000000003
Error:0.11390625000000001 Prediction:0.4625


Wir verwenden die Prognose unseres Netzes nun direkt in der Berechnung des Fehlers: 
```
error = (pred - goal_pred) ** 2
```
Fügen wir die ursprüngliche Berechnung in diesem Term ein, so erhalten wir:
```
error = ((input * weight) - goal_pred) ** 2
```
Dies verändert das Ergebnis der Berechnung nicht. Wir verbinden so einfach zwei Codezeilen und berechnen den Fehler direkt.

Fügen wir nun die Werte für Input und goal_pred ein, die wir zu Beginn festgelegt haben, erhalten wir folgenden Ausdruck:
```
error = ((0.5 * weight) - 0.8) ** 2
```
Nun ist ersichtlich, dass wir für jedes Wertpaar aus input und goal_pred eine exakte Gleichung zwischen Fehler und Gewicht anschreiben können.

<table>
<tr>
<td>
Wir können nun die Änderung des Prognosefehlers abhänngig von einer Änderung der Gewichte berechnen. Der Funktionsgraph zeigt alle Wert von error für alle Werte von weight. Da es sich um eine exponentielle Funktion handelt, ist der Funktionsgraph "schüsselförmig". Der schwarze Punkt markiert die aktuelle Position, entsprechend der aktuellen Werte für ```weight``` und ```error```. Im Minimum der Funktion (strichlierter Kreis) hätten wir einen Wert von 0 für ```error```.

Wir können also feststellen, dass die Steigung der Funktion in die Richtung des Optimums zeigt - egal aus welcher Richtung wir uns nähern.
</td>
<td width="400">
<img src="images/gradient_descent_01.png" width=400/>
</td>
</tr>
</table>

## Berechnung der Upates für die Gewichte über mehrere Iterationen hinweg

In [7]:
weight, goal_pred, input = (0.0, 0.8, 1.1)
for iteration in range(4):
    print("-----\nWeight:" + str(weight))
    pred = 
    error = 
    delta = 
    weight_delta = 
    weight = 
    print("Error:" + str(error) + " Prediction:" + str(pred))
    print("Delta:" + str(delta) + " Weight Delta:" + str(weight_delta))

-----
Weight:0.0
Error:0.6400000000000001 Prediction:0.0
Delta:-0.8 Weight Delta:-0.8800000000000001
-----
Weight:0.8800000000000001
Error:0.02822400000000005 Prediction:0.9680000000000002
Delta:0.16800000000000015 Weight Delta:0.1848000000000002
-----
Weight:0.6951999999999999
Error:0.0012446784000000064 Prediction:0.76472
Delta:-0.03528000000000009 Weight Delta:-0.0388080000000001
-----
Weight:0.734008
Error:5.4890317439999896e-05 Prediction:0.8074088
Delta:0.007408799999999993 Weight Delta:0.008149679999999992


## Breaking Gradient Descent
In manchen Fällen schießt unser Netz über das Ziel hinaus:

In [9]:
goal_pred = 0.8
input = 2
for iteration in range(20):
    pred = 
    error = 
    delta = 
    weight_delta = 
    weight = 
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:5.733418687992733 Prediction:3.1944558229361286
Error:51.600768191934606 Prediction:-6.383367468808387
Error:464.40691372741134 Prediction:22.350102406425158
Error:4179.662223546703 Prediction:-63.85030721927547
Error:37616.960011920324 Prediction:194.75092165782644
Error:338552.64010728284 Prediction:-581.0527649734793
Error:3046973.7609655457 Prediction:1746.3582949204376
Error:27422763.848689917 Prediction:-5235.874884761313
Error:246804874.63820928 Prediction:15710.82465428394
Error:2221243871.7438836 Prediction:-47129.273962851825
Error:19991194845.69496 Prediction:141391.0218885555
Error:179920753611.25464 Prediction:-424169.8656656665
Error:1619286782501.2917 Prediction:1272512.7969969995
Error:14573581042511.623 Prediction:-3817535.1909909984
Error:131162229382604.56 Prediction:11452608.772972994
Error:1180460064443440.8 Prediction:-34357823.11891898
Error:1.0624140579990966e+16 Prediction:103073472.55675691
Error:9.56172652199187e+16 Prediction:-309220414.47027075
Error:

## Gradient Descent mit Alpha

In [11]:
weight = 0.5
goal_pred = 0.8
input = 2
alpha = 0.1
for iteration in range(20):
    pred = 
    error = 
    derivative = 
    weight = 
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.03999999999999998 Prediction:1.0
Error:0.0144 Prediction:0.92
Error:0.005183999999999993 Prediction:0.872
Error:0.0018662400000000014 Prediction:0.8432000000000001
Error:0.0006718464000000028 Prediction:0.8259200000000001
Error:0.00024186470400000033 Prediction:0.815552
Error:8.70712934399997e-05 Prediction:0.8093312
Error:3.134566563839939e-05 Prediction:0.80559872
Error:1.1284439629823931e-05 Prediction:0.803359232
Error:4.062398266736526e-06 Prediction:0.8020155392
Error:1.4624633760252567e-06 Prediction:0.8012093235200001
Error:5.264868153690924e-07 Prediction:0.8007255941120001
Error:1.8953525353291194e-07 Prediction:0.8004353564672001
Error:6.82326912718715e-08 Prediction:0.8002612138803201
Error:2.456376885786678e-08 Prediction:0.8001567283281921
Error:8.842956788836216e-09 Prediction:0.8000940369969153
Error:3.1834644439835434e-09 Prediction:0.8000564221981492
Error:1.1460471998340758e-09 Prediction:0.8000338533188895
Error:4.125769919393652e-10 Prediction:0.80002031199

## Gradient Descent über mehrere Iterationen

In [6]:
def neural_network(input, weights):
    out = 0
    for i in range(len(input)):
        out += 
    return out

In [7]:
def ele_mul(scalar, vector):
    out = [0,0,0]
    for i in range(len(out)):
        out[i] = 
    return out

In [8]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]
alpha = 0.01
weights = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(3):
    pred = neural_network(input,weights)
    error = 
    delta = 
    weight_deltas = 
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("Weights:" + str(weights))
    print("Weight_Deltas:")
    print(str(weight_deltas))
    print()
    for i in range(len(weights)):
        

Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
Weights:[0.1, 0.2, -0.1]
Weight_Deltas:
[-1.189999999999999, -0.09099999999999994, -0.16799999999999987]

Iteration:2
Pred:0.9637574999999999
Error:0.0013135188062500048
Delta:-0.036242500000000066
Weights:[0.1119, 0.20091, -0.09832]
Weight_Deltas:
[-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]

Iteration:3
Pred:0.9906177228125002
Error:8.802712522307997e-05
Delta:-0.009382277187499843
Weights:[0.11498061250000001, 0.20114557625, -0.09788509000000001]
Weight_Deltas:
[-0.07974935609374867, -0.006098480171874899, -0.011258732624999811]



# Gradient Descent mit mehreren Outputs

In [23]:
def ele_mul(number,vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

In [24]:
# instead of predicting just whether the team won or lost,
# now we're also predicting whether they are happy/sad AND the percentage
# of the team that is hurt. We are making this prediction using only
# the current win/loss record

weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    pred = ele_mul(input,weights)
    return pred

In [25]:
wlrec = [0.9, 1.0, 1.0, 0.9]
hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]
input = wlrec[0]
true = [hurt[0], win[0], sad[0]]
pred = neural_network(input,weights)
error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(true)):
    error[i] = 
    delta = 
    weight_deltas = 
    
alpha = 0.1
for i in range(len(weights)):
    weights[i] -= (

# Gradient Descent mit mehreren Inputs auf mehrere Outputs 

Helper Functions

In [34]:
import numpy as np

In [39]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += 
    return output

In [35]:
def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = np.zeros(len(vect))
    for i in range(len(vect)):
        output[i] = 
    return output

In [63]:
def outer_prod(vec_a, vec_b):    
    out = np.zeros(shape=(len(vec_a), len(vec_b)))
    for i in range(len(vec_a)):
        for j in range(len(vec_b)):
            out[i][j] = 
    return out

In [30]:
weights = [ [0.1, 0.1, -0.3],  #hurt?
            [0.1, 0.2, 0.0 ],  #win?
            [0.0, 1.3, 0.1 ] ] #sad?

def neural_network(input, weights):
    pred = 
    return pred

In [64]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

alpha = 0.01

input = [toes[0], wlrec[0], nfans[0]]
true = [hurt[0], win[0], sad[0]]

pred = neural_network(input, weights)

error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(true)):
   

weight_deltas = 

for i in range(len(weights)):
    for j in range(len(weights[0])):
        
        
print(weight_deltas)

[[-0.58241069 -0.51028729  6.72427731]
 [-0.04453729 -0.03902197  0.51420944]
 [-0.08222269 -0.07204056  0.94930974]]
